// <auto-generated />
using System;
using G1720252401;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G1720252401.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250204151550_20250204-3")]
    partial class _202502043
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("G1720252401.Models.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityID"));

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.HasIndex("CountryID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = 1,
                            CountryID = 1,
                            Name = "Tbilisi"
                        },
                        new
                        {
                            CityID = 2,
                            CountryID = 1,
                            Name = "Batumi"
                        },
                        new
                        {
                            CityID = 3,
                            CountryID = 2,
                            Name = "Rome"
                        },
                        new
                        {
                            CityID = 4,
                            CountryID = 2,
                            Name = "Florence"
                        },
                        new
                        {
                            CityID = 5,
                            CountryID = 3,
                            Name = "Paris"
                        },
                        new
                        {
                            CityID = 6,
                            CountryID = 3,
                            Name = "Nice"
                        },
                        new
                        {
                            CityID = 7,
                            CountryID = 4,
                            Name = "Barcelona"
                        },
                        new
                        {
                            CityID = 8,
                            CountryID = 4,
                            Name = "Madrid"
                        },
                        new
                        {
                            CityID = 9,
                            CountryID = 5,
                            Name = "New York"
                        },
                        new
                        {
                            CityID = 10,
                            CountryID = 5,
                            Name = "Los Angeles"
                        });
                });

            modelBuilder.Entity("G1720252401.Models.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = 1,
                            Name = "Georgia"
                        },
                        new
                        {
                            CountryID = 2,
                            Name = "Italy"
                        },
                        new
                        {
                            CountryID = 3,
                            Name = "France"
                        },
                        new
                        {
                            CountryID = 4,
                            Name = "Spain"
                        },
                        new
                        {
                            CountryID = 5,
                            Name = "USA"
                        });
                });

            modelBuilder.Entity("G1720252401.Models.Hotel", b =>
                {
                    b.Property<int>("HotelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelID"));

                    b.Property<string>("AdditionalServices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<bool>("MealIncluded")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("HotelID");

                    b.HasIndex("CityID");

                    b.ToTable("Hotels", t =>
                        {
                            t.HasCheckConstraint("CK_Hotel_Stars", "Stars between 1 and 5");
                        });

                    b.HasData(
                        new
                        {
                            HotelID = 1,
                            AdditionalServices = "Laundry,WiFi,Satellite TV",
                            CityID = 1,
                            MealIncluded = true,
                            Name = "Hotel Tbilisi",
                            PricePerNight = 200.00m,
                            Stars = 5
                        },
                        new
                        {
                            HotelID = 2,
                            AdditionalServices = "WiFi,Swimming Pool",
                            CityID = 2,
                            MealIncluded = false,
                            Name = "Hotel Batumi",
                            PricePerNight = 150.00m,
                            Stars = 4
                        },
                        new
                        {
                            HotelID = 3,
                            AdditionalServices = "Gym,WiFi,Restaurant",
                            CityID = 3,
                            MealIncluded = true,
                            Name = "Hotel Rome",
                            PricePerNight = 250.00m,
                            Stars = 5
                        });
                });

            modelBuilder.Entity("G1720252401.Models.Tour", b =>
                {
                    b.Property<int>("TourID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TourID");

                    b.ToTable("Tours", t =>
                        {
                            t.HasCheckConstraint("CK_Tour_Code", "LEN(Code) = 5");
                        });

                    b.HasData(
                        new
                        {
                            TourID = 1,
                            Code = "T0011",
                            Duration = 7,
                            Name = "Rome and Florence Tour",
                            TotalPrice = 1500.00m
                        },
                        new
                        {
                            TourID = 2,
                            Code = "T0022",
                            Duration = 6,
                            Name = "Paris and Nice Tour",
                            TotalPrice = 1400.00m
                        });
                });

            modelBuilder.Entity("G1720252401.Models.TourCity", b =>
                {
                    b.Property<int>("TourID")
                        .HasColumnType("int");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.HasKey("TourID", "CityID");

                    b.HasIndex("CityID");

                    b.ToTable("TourCities");

                    b.HasData(
                        new
                        {
                            TourID = 1,
                            CityID = 3,
                            Days = 4
                        },
                        new
                        {
                            TourID = 1,
                            CityID = 4,
                            Days = 3
                        });
                });

            modelBuilder.Entity("G1720252401.Models.Tourist", b =>
                {
                    b.Property<int>("TouristID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TouristID"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("TouristID");

                    b.HasIndex("PassportNumber")
                        .IsUnique();

                    b.ToTable("Tourists", t =>
                        {
                            t.HasCheckConstraint("CK_Tourist_PassportNumber", "LEN(PassportNumber) = 11");
                        });

                    b.HasData(
                        new
                        {
                            TouristID = 1,
                            BirthDate = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactPhone = "+1234567890",
                            FirstName = "John",
                            LastName = "Doe",
                            PassportNumber = "12345678901"
                        },
                        new
                        {
                            TouristID = 2,
                            BirthDate = new DateTime(1990, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactPhone = "+1234567891",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PassportNumber = "12345678902"
                        });
                });

            modelBuilder.Entity("G1720252401.Models.TouristTour", b =>
                {
                    b.Property<int>("TourID")
                        .HasColumnType("int");

                    b.Property<int>("TouristID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TourID", "TouristID");

                    b.HasIndex("TouristID");

                    b.ToTable("TouristTours");

                    b.HasData(
                        new
                        {
                            TourID = 1,
                            TouristID = 1,
                            DepartureDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2023, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TourID = 2,
                            TouristID = 2,
                            DepartureDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2023, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("G1720252401.Models.City", b =>
                {
                    b.HasOne("G1720252401.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("G1720252401.Models.Hotel", b =>
                {
                    b.HasOne("G1720252401.Models.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("G1720252401.Models.TourCity", b =>
                {
                    b.HasOne("G1720252401.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G1720252401.Models.Tour", "Tour")
                        .WithMany("TourCities")
                        .HasForeignKey("TourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("G1720252401.Models.TouristTour", b =>
                {
                    b.HasOne("G1720252401.Models.Tour", "Tour")
                        .WithMany("TouristTours")
                        .HasForeignKey("TourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G1720252401.Models.Tourist", "Tourist")
                        .WithMany("TouristTours")
                        .HasForeignKey("TouristID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("G1720252401.Models.City", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("G1720252401.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("G1720252401.Models.Tour", b =>
                {
                    b.Navigation("TourCities");

                    b.Navigation("TouristTours");
                });

            modelBuilder.Entity("G1720252401.Models.Tourist", b =>
                {
                    b.Navigation("TouristTours");
                });
#pragma warning restore 612, 618
        }
    }
}
